//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.google.javascript.jscomp {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class DiagnosticGroups : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_forName0;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_GLOBAL_THIS1;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_DEPRECATED2;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_VISIBILITY3;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_CONSTANT_PROPERTY4;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_NON_STANDARD_JSDOC5;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_ACCESS_CONTROLS6;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_INVALID_CASTS7;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_FILEOVERVIEW_JSDOC8;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_STRICT_MODULE_DEP_CHECK9;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_EXTERNS_VALIDATION10;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_AMBIGUOUS_FUNCTION_DECL11;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_UNKNOWN_DEFINES12;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_TWEAKS13;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_MISSING_PROPERTIES14;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_INTERNET_EXPLORER_CHECKS15;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_UNDEFINED_VARIABLES16;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_UNDEFINED_NAMES17;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_DEBUGGER_STATEMENT_PRESENT18;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_CHECK_REGEXP19;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_CHECK_TYPES20;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_CHECK_VARIABLES21;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_CHECK_USELESS_CODE22;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_CONST23;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_TYPE_INVALIDATION24;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_DUPLICATE_VARS25;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_ES5_STRICT26;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_CHECK_PROVIDES27;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_DUPLICATE_MESSAGE28;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorDiagnosticGroups29;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public DiagnosticGroups() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n__ctorDiagnosticGroups29, this);
            }
        }
        
        protected DiagnosticGroups(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.google.javascript.jscomp.DiagnosticGroups.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object GLOBAL_THIS {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_GLOBAL_THIS1));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object DEPRECATED {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_DEPRECATED2));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object VISIBILITY {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_VISIBILITY3));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object CONSTANT_PROPERTY {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_CONSTANT_PROPERTY4));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object NON_STANDARD_JSDOC {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_NON_STANDARD_JSDOC5));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object ACCESS_CONTROLS {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_ACCESS_CONTROLS6));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object INVALID_CASTS {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_INVALID_CASTS7));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object FILEOVERVIEW_JSDOC {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_FILEOVERVIEW_JSDOC8));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object STRICT_MODULE_DEP_CHECK {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_STRICT_MODULE_DEP_CHECK9));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object EXTERNS_VALIDATION {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_EXTERNS_VALIDATION10));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object AMBIGUOUS_FUNCTION_DECL {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_AMBIGUOUS_FUNCTION_DECL11));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object UNKNOWN_DEFINES {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_UNKNOWN_DEFINES12));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object TWEAKS {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_TWEAKS13));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object MISSING_PROPERTIES {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_MISSING_PROPERTIES14));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object INTERNET_EXPLORER_CHECKS {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_INTERNET_EXPLORER_CHECKS15));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object UNDEFINED_VARIABLES {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_UNDEFINED_VARIABLES16));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object UNDEFINED_NAMES {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_UNDEFINED_NAMES17));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object DEBUGGER_STATEMENT_PRESENT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_DEBUGGER_STATEMENT_PRESENT18));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object CHECK_REGEXP {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_CHECK_REGEXP19));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object CHECK_TYPES {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_CHECK_TYPES20));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object CHECK_VARIABLES {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_CHECK_VARIABLES21));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object CHECK_USELESS_CODE {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_CHECK_USELESS_CODE22));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object CONST {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_CONST23));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object TYPE_INVALIDATION {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_TYPE_INVALIDATION24));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object DUPLICATE_VARS {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_DUPLICATE_VARS25));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object ES5_STRICT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_ES5_STRICT26));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object CHECK_PROVIDES {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_CHECK_PROVIDES27));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public static global::java.lang.Object DUPLICATE_MESSAGE {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_DUPLICATE_MESSAGE28));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.google.javascript.jscomp.DiagnosticGroups.staticClass = @__class;
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_forName0 = @__env.GetMethodID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "forName", "(Ljava/lang/String;)Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_GLOBAL_THIS1 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "GLOBAL_THIS", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_DEPRECATED2 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "DEPRECATED", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_VISIBILITY3 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "VISIBILITY", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_CONSTANT_PROPERTY4 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "CONSTANT_PROPERTY", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_NON_STANDARD_JSDOC5 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "NON_STANDARD_JSDOC", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_ACCESS_CONTROLS6 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "ACCESS_CONTROLS", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_INVALID_CASTS7 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "INVALID_CASTS", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_FILEOVERVIEW_JSDOC8 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "FILEOVERVIEW_JSDOC", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_STRICT_MODULE_DEP_CHECK9 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "STRICT_MODULE_DEP_CHECK", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_EXTERNS_VALIDATION10 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "EXTERNS_VALIDATION", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_AMBIGUOUS_FUNCTION_DECL11 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "AMBIGUOUS_FUNCTION_DECL", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_UNKNOWN_DEFINES12 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "UNKNOWN_DEFINES", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_TWEAKS13 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "TWEAKS", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_MISSING_PROPERTIES14 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "MISSING_PROPERTIES", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_INTERNET_EXPLORER_CHECKS15 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "INTERNET_EXPLORER_CHECKS", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_UNDEFINED_VARIABLES16 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "UNDEFINED_VARIABLES", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_UNDEFINED_NAMES17 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "UNDEFINED_NAMES", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_DEBUGGER_STATEMENT_PRESENT18 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "DEBUGGER_STATEMENT_PRESENT", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_CHECK_REGEXP19 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "CHECK_REGEXP", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_CHECK_TYPES20 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "CHECK_TYPES", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_CHECK_VARIABLES21 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "CHECK_VARIABLES", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_CHECK_USELESS_CODE22 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "CHECK_USELESS_CODE", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_CONST23 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "CONST", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_TYPE_INVALIDATION24 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "TYPE_INVALIDATION", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_DUPLICATE_VARS25 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "DUPLICATE_VARS", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_ES5_STRICT26 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "ES5_STRICT", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_CHECK_PROVIDES27 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "CHECK_PROVIDES", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n_DUPLICATE_MESSAGE28 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "DUPLICATE_MESSAGE", "Lcom/google/javascript/jscomp/DiagnosticGroup;");
            global::com.google.javascript.jscomp.DiagnosticGroups.j4n__ctorDiagnosticGroups29 = @__env.GetMethodID(global::com.google.javascript.jscomp.DiagnosticGroups.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/google/javascript/jscomp/DiagnosticGroup;")]
        public virtual global::java.lang.Object forName(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.DiagnosticGroups.j4n_forName0, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.google.javascript.jscomp.DiagnosticGroups(@__env);
            }
        }
    }
    #endregion
}
