//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.google.javascript.jscomp {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class CompilationLevel : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_values0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_valueOf1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setOptionsForCompilationLevel2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setDebugOptionsForCompilationLevel3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setTypeBasedOptimizationOptions4;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_WHITESPACE_ONLY5;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_SIMPLE_OPTIMIZATIONS6;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_ADVANCED_OPTIMIZATIONS7;
        
        protected CompilationLevel(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.google.javascript.jscomp.CompilationLevel.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/CompilationLevel;")]
        public static global::com.google.javascript.jscomp.CompilationLevel WHITESPACE_ONLY {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.CompilationLevel>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.CompilationLevel.staticClass, global::com.google.javascript.jscomp.CompilationLevel.j4n_WHITESPACE_ONLY5));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/CompilationLevel;")]
        public static global::com.google.javascript.jscomp.CompilationLevel SIMPLE_OPTIMIZATIONS {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.CompilationLevel>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.CompilationLevel.staticClass, global::com.google.javascript.jscomp.CompilationLevel.j4n_SIMPLE_OPTIMIZATIONS6));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/CompilationLevel;")]
        public static global::com.google.javascript.jscomp.CompilationLevel ADVANCED_OPTIMIZATIONS {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.CompilationLevel>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.CompilationLevel.staticClass, global::com.google.javascript.jscomp.CompilationLevel.j4n_ADVANCED_OPTIMIZATIONS7));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.google.javascript.jscomp.CompilationLevel.staticClass = @__class;
            global::com.google.javascript.jscomp.CompilationLevel.j4n_values0 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.CompilationLevel.staticClass, "values", "()[Lcom/google/javascript/jscomp/CompilationLevel;");
            global::com.google.javascript.jscomp.CompilationLevel.j4n_valueOf1 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.CompilationLevel.staticClass, "valueOf", "(Ljava/lang/String;)Lcom/google/javascript/jscomp/CompilationLevel;");
            global::com.google.javascript.jscomp.CompilationLevel.j4n_setOptionsForCompilationLevel2 = @__env.GetMethodID(global::com.google.javascript.jscomp.CompilationLevel.staticClass, "setOptionsForCompilationLevel", "(Lcom/google/javascript/jscomp/CompilerOptions;)V");
            global::com.google.javascript.jscomp.CompilationLevel.j4n_setDebugOptionsForCompilationLevel3 = @__env.GetMethodID(global::com.google.javascript.jscomp.CompilationLevel.staticClass, "setDebugOptionsForCompilationLevel", "(Lcom/google/javascript/jscomp/CompilerOptions;)V");
            global::com.google.javascript.jscomp.CompilationLevel.j4n_setTypeBasedOptimizationOptions4 = @__env.GetMethodID(global::com.google.javascript.jscomp.CompilationLevel.staticClass, "setTypeBasedOptimizationOptions", "(Lcom/google/javascript/jscomp/CompilerOptions;)V");
            global::com.google.javascript.jscomp.CompilationLevel.j4n_WHITESPACE_ONLY5 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.CompilationLevel.staticClass, "WHITESPACE_ONLY", "Lcom/google/javascript/jscomp/CompilationLevel;");
            global::com.google.javascript.jscomp.CompilationLevel.j4n_SIMPLE_OPTIMIZATIONS6 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.CompilationLevel.staticClass, "SIMPLE_OPTIMIZATIONS", "Lcom/google/javascript/jscomp/CompilationLevel;");
            global::com.google.javascript.jscomp.CompilationLevel.j4n_ADVANCED_OPTIMIZATIONS7 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.CompilationLevel.staticClass, "ADVANCED_OPTIMIZATIONS", "Lcom/google/javascript/jscomp/CompilationLevel;");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()[Lcom/google/javascript/jscomp/CompilationLevel;")]
        public static com.google.javascript.jscomp.CompilationLevel[] values() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2Cp<com.google.javascript.jscomp.CompilationLevel[], global::com.google.javascript.jscomp.CompilationLevel>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.CompilationLevel.staticClass, global::com.google.javascript.jscomp.CompilationLevel.j4n_values0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/google/javascript/jscomp/CompilationLevel;")]
        public static global::com.google.javascript.jscomp.CompilationLevel valueOf(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.CompilationLevel>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.CompilationLevel.staticClass, global::com.google.javascript.jscomp.CompilationLevel.j4n_valueOf1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/CompilerOptions;)V")]
        public virtual void setOptionsForCompilationLevel(global::com.google.javascript.jscomp.CompilerOptions par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.CompilationLevel.j4n_setOptionsForCompilationLevel2, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/CompilerOptions;)V")]
        public virtual void setDebugOptionsForCompilationLevel(global::com.google.javascript.jscomp.CompilerOptions par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.CompilationLevel.j4n_setDebugOptionsForCompilationLevel3, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/CompilerOptions;)V")]
        public virtual void setTypeBasedOptimizationOptions(global::com.google.javascript.jscomp.CompilerOptions par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.CompilationLevel.j4n_setTypeBasedOptimizationOptions4, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.google.javascript.jscomp.CompilationLevel(@__env);
            }
        }
    }
    #endregion
}
