//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.google.javascript.jscomp {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class Compiler : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_init0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_init1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_init2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_optimize3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getState4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_compile5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_compile6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_compile7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_compile8;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_compile9;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_compile10;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_parse11;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_parse12;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_normalize13;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_check14;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setState15;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_initOptions16;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_initModules17;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_hasErrors18;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getResult19;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getErrors20;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getWarnings21;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getMessages22;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_toSource23;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_toSource24;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_toSource25;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setErrorManager26;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_rebuildInputsFromModules27;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_compileModules28;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_disableThreads29;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setPassConfig30;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getTypedScopeCreator31;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_buildKnownSymbolTable32;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_toSourceArray33;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_toSourceArray34;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_processDefines35;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getErrorCount36;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getWarningCount37;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setLoggingLevel38;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getAstDotGraph39;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getInputsById40;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_replaceScript41;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getReleaseVersion42;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getReleaseDate43;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_languageMode44;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getSourceMap45;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_addNewScript46;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_tracker47;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_OPTIMIZE_LOOP_ERROR48;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_MOTION_ITERATIONS_ERROR49;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorCompiler50;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorCompiler51;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorCompiler52;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/io/PrintStream;)V")]
        public Compiler(global::java.io.PrintStream par0) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.NewObject(global::com.google.javascript.jscomp.Compiler.staticClass, global::com.google.javascript.jscomp.Compiler.j4n__ctorCompiler50, this, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public Compiler() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::com.google.javascript.jscomp.Compiler.staticClass, global::com.google.javascript.jscomp.Compiler.j4n__ctorCompiler51, this);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/ErrorManager;)V")]
        public Compiler(global::java.lang.Object par0) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.NewObject(global::com.google.javascript.jscomp.Compiler.staticClass, global::com.google.javascript.jscomp.Compiler.j4n__ctorCompiler52, this, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0));
            }
        }
        
        protected Compiler(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.google.javascript.jscomp.Compiler.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/PerformanceTracker;")]
        public virtual global::java.lang.Object tracker {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetObjectFieldPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_tracker47));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticType;")]
        public static global::java.lang.Object OPTIMIZE_LOOP_ERROR {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.Compiler.staticClass, global::com.google.javascript.jscomp.Compiler.j4n_OPTIMIZE_LOOP_ERROR48));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Lcom/google/javascript/jscomp/DiagnosticType;")]
        public static global::java.lang.Object MOTION_ITERATIONS_ERROR {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.GetStaticObjectFieldPtr(global::com.google.javascript.jscomp.Compiler.staticClass, global::com.google.javascript.jscomp.Compiler.j4n_MOTION_ITERATIONS_ERROR49));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.google.javascript.jscomp.Compiler.staticClass = @__class;
            global::com.google.javascript.jscomp.Compiler.j4n_init0 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "init", "([Lcom/google/javascript/jscomp/JSSourceFile;[Lcom/google/javascript/jscomp/JSMod" +
                    "ule;Lcom/google/javascript/jscomp/CompilerOptions;)V");
            global::com.google.javascript.jscomp.Compiler.j4n_init1 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "init", "(Ljava/util/List;Ljava/util/List;Lcom/google/javascript/jscomp/CompilerOptions;)V" +
                    "");
            global::com.google.javascript.jscomp.Compiler.j4n_init2 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "init", "([Lcom/google/javascript/jscomp/JSSourceFile;[Lcom/google/javascript/jscomp/JSSou" +
                    "rceFile;Lcom/google/javascript/jscomp/CompilerOptions;)V");
            global::com.google.javascript.jscomp.Compiler.j4n_optimize3 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "optimize", "()V");
            global::com.google.javascript.jscomp.Compiler.j4n_getState4 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "getState", "()Lcom/google/javascript/jscomp/Compiler$IntermediateState;");
            global::com.google.javascript.jscomp.Compiler.j4n_compile5 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "compile", "(Lcom/google/javascript/jscomp/SourceFile;[Lcom/google/javascript/jscomp/JSSource" +
                    "File;Lcom/google/javascript/jscomp/CompilerOptions;)Lcom/google/javascript/jscom" +
                    "p/Result;");
            global::com.google.javascript.jscomp.Compiler.j4n_compile6 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "compile", "(Lcom/google/javascript/jscomp/SourceFile;Lcom/google/javascript/jscomp/SourceFil" +
                    "e;Lcom/google/javascript/jscomp/CompilerOptions;)Lcom/google/javascript/jscomp/R" +
                    "esult;");
            global::com.google.javascript.jscomp.Compiler.j4n_compile7 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "compile", "([Lcom/google/javascript/jscomp/JSSourceFile;[Lcom/google/javascript/jscomp/JSSou" +
                    "rceFile;Lcom/google/javascript/jscomp/CompilerOptions;)Lcom/google/javascript/js" +
                    "comp/Result;");
            global::com.google.javascript.jscomp.Compiler.j4n_compile8 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "compile", "(Lcom/google/javascript/jscomp/JSSourceFile;[Lcom/google/javascript/jscomp/JSModu" +
                    "le;Lcom/google/javascript/jscomp/CompilerOptions;)Lcom/google/javascript/jscomp/" +
                    "Result;");
            global::com.google.javascript.jscomp.Compiler.j4n_compile9 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "compile", "([Lcom/google/javascript/jscomp/JSSourceFile;[Lcom/google/javascript/jscomp/JSMod" +
                    "ule;Lcom/google/javascript/jscomp/CompilerOptions;)Lcom/google/javascript/jscomp" +
                    "/Result;");
            global::com.google.javascript.jscomp.Compiler.j4n_compile10 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "compile", "(Ljava/util/List;Ljava/util/List;Lcom/google/javascript/jscomp/CompilerOptions;)L" +
                    "com/google/javascript/jscomp/Result;");
            global::com.google.javascript.jscomp.Compiler.j4n_parse11 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "parse", "()V");
            global::com.google.javascript.jscomp.Compiler.j4n_parse12 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "parse", "(Lcom/google/javascript/jscomp/SourceFile;)Lcom/google/javascript/rhino/Node;");
            global::com.google.javascript.jscomp.Compiler.j4n_normalize13 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "normalize", "()V");
            global::com.google.javascript.jscomp.Compiler.j4n_check14 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "check", "()V");
            global::com.google.javascript.jscomp.Compiler.j4n_setState15 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "setState", "(Lcom/google/javascript/jscomp/Compiler$IntermediateState;)V");
            global::com.google.javascript.jscomp.Compiler.j4n_initOptions16 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "initOptions", "(Lcom/google/javascript/jscomp/CompilerOptions;)V");
            global::com.google.javascript.jscomp.Compiler.j4n_initModules17 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "initModules", "(Ljava/util/List;Ljava/util/List;Lcom/google/javascript/jscomp/CompilerOptions;)V" +
                    "");
            global::com.google.javascript.jscomp.Compiler.j4n_hasErrors18 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "hasErrors", "()Z");
            global::com.google.javascript.jscomp.Compiler.j4n_getResult19 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "getResult", "()Lcom/google/javascript/jscomp/Result;");
            global::com.google.javascript.jscomp.Compiler.j4n_getErrors20 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "getErrors", "()[Lcom/google/javascript/jscomp/JSError;");
            global::com.google.javascript.jscomp.Compiler.j4n_getWarnings21 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "getWarnings", "()[Lcom/google/javascript/jscomp/JSError;");
            global::com.google.javascript.jscomp.Compiler.j4n_getMessages22 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "getMessages", "()[Lcom/google/javascript/jscomp/JSError;");
            global::com.google.javascript.jscomp.Compiler.j4n_toSource23 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "toSource", "()Ljava/lang/String;");
            global::com.google.javascript.jscomp.Compiler.j4n_toSource24 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "toSource", "(Lcom/google/javascript/jscomp/JSModule;)Ljava/lang/String;");
            global::com.google.javascript.jscomp.Compiler.j4n_toSource25 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "toSource", "(Lcom/google/javascript/jscomp/Compiler$CodeBuilder;ILcom/google/javascript/rhino" +
                    "/Node;)V");
            global::com.google.javascript.jscomp.Compiler.j4n_setErrorManager26 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "setErrorManager", "(Lcom/google/javascript/jscomp/ErrorManager;)V");
            global::com.google.javascript.jscomp.Compiler.j4n_rebuildInputsFromModules27 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "rebuildInputsFromModules", "()V");
            global::com.google.javascript.jscomp.Compiler.j4n_compileModules28 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "compileModules", "(Ljava/util/List;Ljava/util/List;Lcom/google/javascript/jscomp/CompilerOptions;)L" +
                    "com/google/javascript/jscomp/Result;");
            global::com.google.javascript.jscomp.Compiler.j4n_disableThreads29 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "disableThreads", "()V");
            global::com.google.javascript.jscomp.Compiler.j4n_setPassConfig30 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "setPassConfig", "(Lcom/google/javascript/jscomp/PassConfig;)V");
            global::com.google.javascript.jscomp.Compiler.j4n_getTypedScopeCreator31 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "getTypedScopeCreator", "()Lcom/google/javascript/jscomp/MemoizedScopeCreator;");
            global::com.google.javascript.jscomp.Compiler.j4n_buildKnownSymbolTable32 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "buildKnownSymbolTable", "()Lcom/google/javascript/jscomp/SymbolTable;");
            global::com.google.javascript.jscomp.Compiler.j4n_toSourceArray33 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "toSourceArray", "(Lcom/google/javascript/jscomp/JSModule;)[Ljava/lang/String;");
            global::com.google.javascript.jscomp.Compiler.j4n_toSourceArray34 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "toSourceArray", "()[Ljava/lang/String;");
            global::com.google.javascript.jscomp.Compiler.j4n_processDefines35 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "processDefines", "()V");
            global::com.google.javascript.jscomp.Compiler.j4n_getErrorCount36 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "getErrorCount", "()I");
            global::com.google.javascript.jscomp.Compiler.j4n_getWarningCount37 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "getWarningCount", "()I");
            global::com.google.javascript.jscomp.Compiler.j4n_setLoggingLevel38 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "setLoggingLevel", "(Ljava/util/logging/Level;)V");
            global::com.google.javascript.jscomp.Compiler.j4n_getAstDotGraph39 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "getAstDotGraph", "()Ljava/lang/String;");
            global::com.google.javascript.jscomp.Compiler.j4n_getInputsById40 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "getInputsById", "()Ljava/util/Map;");
            global::com.google.javascript.jscomp.Compiler.j4n_replaceScript41 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "replaceScript", "(Lcom/google/javascript/jscomp/JsAst;)V");
            global::com.google.javascript.jscomp.Compiler.j4n_getReleaseVersion42 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "getReleaseVersion", "()Ljava/lang/String;");
            global::com.google.javascript.jscomp.Compiler.j4n_getReleaseDate43 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "getReleaseDate", "()Ljava/lang/String;");
            global::com.google.javascript.jscomp.Compiler.j4n_languageMode44 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "languageMode", "()Lcom/google/javascript/jscomp/CompilerOptions$LanguageMode;");
            global::com.google.javascript.jscomp.Compiler.j4n_getSourceMap45 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "getSourceMap", "()Lcom/google/javascript/jscomp/SourceMap;");
            global::com.google.javascript.jscomp.Compiler.j4n_addNewScript46 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "addNewScript", "(Lcom/google/javascript/jscomp/JsAst;)V");
            global::com.google.javascript.jscomp.Compiler.j4n_tracker47 = @__env.GetFieldID(global::com.google.javascript.jscomp.Compiler.staticClass, "tracker", "Lcom/google/javascript/jscomp/PerformanceTracker;");
            global::com.google.javascript.jscomp.Compiler.j4n_OPTIMIZE_LOOP_ERROR48 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.Compiler.staticClass, "OPTIMIZE_LOOP_ERROR", "Lcom/google/javascript/jscomp/DiagnosticType;");
            global::com.google.javascript.jscomp.Compiler.j4n_MOTION_ITERATIONS_ERROR49 = @__env.GetStaticFieldID(global::com.google.javascript.jscomp.Compiler.staticClass, "MOTION_ITERATIONS_ERROR", "Lcom/google/javascript/jscomp/DiagnosticType;");
            global::com.google.javascript.jscomp.Compiler.j4n__ctorCompiler50 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "<init>", "(Ljava/io/PrintStream;)V");
            global::com.google.javascript.jscomp.Compiler.j4n__ctorCompiler51 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "<init>", "()V");
            global::com.google.javascript.jscomp.Compiler.j4n__ctorCompiler52 = @__env.GetMethodID(global::com.google.javascript.jscomp.Compiler.staticClass, "<init>", "(Lcom/google/javascript/jscomp/ErrorManager;)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("([Lcom/google/javascript/jscomp/JSSourceFile;[Lcom/google/javascript/jscomp/JSMod" +
            "ule;Lcom/google/javascript/jscomp/CompilerOptions;)V")]
        public virtual void init(com.google.javascript.jscomp.JSSourceFile[] par0, java.lang.Object[] par1, global::com.google.javascript.jscomp.CompilerOptions par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_init0, global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/util/List;Ljava/util/List;Lcom/google/javascript/jscomp/CompilerOptions;)V" +
            "")]
        public virtual void init(global::java.util.List par0, global::java.util.List par1, global::com.google.javascript.jscomp.CompilerOptions par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_init1, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.util.List>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.util.List>(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("([Lcom/google/javascript/jscomp/JSSourceFile;[Lcom/google/javascript/jscomp/JSSou" +
            "rceFile;Lcom/google/javascript/jscomp/CompilerOptions;)V")]
        public virtual void init(com.google.javascript.jscomp.JSSourceFile[] par0, com.google.javascript.jscomp.JSSourceFile[] par1, global::com.google.javascript.jscomp.CompilerOptions par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_init2, global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void optimize() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_optimize3);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lcom/google/javascript/jscomp/Compiler$IntermediateState;")]
        public virtual global::java.lang.Object getState() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_getState4));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/SourceFile;[Lcom/google/javascript/jscomp/JSSource" +
            "File;Lcom/google/javascript/jscomp/CompilerOptions;)Lcom/google/javascript/jscom" +
            "p/Result;")]
        public virtual global::com.google.javascript.jscomp.Result compile(global::com.google.javascript.jscomp.SourceFile par0, com.google.javascript.jscomp.JSSourceFile[] par1, global::com.google.javascript.jscomp.CompilerOptions par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.Result>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_compile5, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/SourceFile;Lcom/google/javascript/jscomp/SourceFil" +
            "e;Lcom/google/javascript/jscomp/CompilerOptions;)Lcom/google/javascript/jscomp/R" +
            "esult;")]
        public virtual global::com.google.javascript.jscomp.Result compile(global::com.google.javascript.jscomp.SourceFile par0, global::com.google.javascript.jscomp.SourceFile par1, global::com.google.javascript.jscomp.CompilerOptions par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.Result>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_compile6, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("([Lcom/google/javascript/jscomp/JSSourceFile;[Lcom/google/javascript/jscomp/JSSou" +
            "rceFile;Lcom/google/javascript/jscomp/CompilerOptions;)Lcom/google/javascript/js" +
            "comp/Result;")]
        public virtual global::com.google.javascript.jscomp.Result compile(com.google.javascript.jscomp.JSSourceFile[] par0, com.google.javascript.jscomp.JSSourceFile[] par1, global::com.google.javascript.jscomp.CompilerOptions par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.Result>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_compile7, global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/JSSourceFile;[Lcom/google/javascript/jscomp/JSModu" +
            "le;Lcom/google/javascript/jscomp/CompilerOptions;)Lcom/google/javascript/jscomp/" +
            "Result;")]
        public virtual global::com.google.javascript.jscomp.Result compile(global::com.google.javascript.jscomp.JSSourceFile par0, java.lang.Object[] par1, global::com.google.javascript.jscomp.CompilerOptions par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.Result>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_compile8, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("([Lcom/google/javascript/jscomp/JSSourceFile;[Lcom/google/javascript/jscomp/JSMod" +
            "ule;Lcom/google/javascript/jscomp/CompilerOptions;)Lcom/google/javascript/jscomp" +
            "/Result;")]
        public virtual global::com.google.javascript.jscomp.Result compile(com.google.javascript.jscomp.JSSourceFile[] par0, java.lang.Object[] par1, global::com.google.javascript.jscomp.CompilerOptions par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.Result>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_compile9, global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/util/List;Ljava/util/List;Lcom/google/javascript/jscomp/CompilerOptions;)L" +
            "com/google/javascript/jscomp/Result;")]
        public virtual global::com.google.javascript.jscomp.Result compile(global::java.util.List par0, global::java.util.List par1, global::com.google.javascript.jscomp.CompilerOptions par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.Result>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_compile10, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.util.List>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.util.List>(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void parse() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_parse11);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/SourceFile;)Lcom/google/javascript/rhino/Node;")]
        public virtual global::java.lang.Object parse(global::com.google.javascript.jscomp.SourceFile par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_parse12, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void normalize() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_normalize13);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void check() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_check14);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/Compiler$IntermediateState;)V")]
        public virtual void setState(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_setState15, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/CompilerOptions;)V")]
        public virtual void initOptions(global::com.google.javascript.jscomp.CompilerOptions par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_initOptions16, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/util/List;Ljava/util/List;Lcom/google/javascript/jscomp/CompilerOptions;)V" +
            "")]
        public virtual void initModules(global::java.util.List par0, global::java.util.List par1, global::com.google.javascript.jscomp.CompilerOptions par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_initModules17, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.util.List>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.util.List>(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public virtual bool hasErrors() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_hasErrors18)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lcom/google/javascript/jscomp/Result;")]
        public virtual global::com.google.javascript.jscomp.Result getResult() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.Result>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_getResult19));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()[Lcom/google/javascript/jscomp/JSError;")]
        public virtual com.google.javascript.jscomp.JSError[] getErrors() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2Cp<com.google.javascript.jscomp.JSError[], global::com.google.javascript.jscomp.JSError>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_getErrors20));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()[Lcom/google/javascript/jscomp/JSError;")]
        public virtual com.google.javascript.jscomp.JSError[] getWarnings() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2Cp<com.google.javascript.jscomp.JSError[], global::com.google.javascript.jscomp.JSError>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_getWarnings21));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()[Lcom/google/javascript/jscomp/JSError;")]
        public virtual com.google.javascript.jscomp.JSError[] getMessages() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2Cp<com.google.javascript.jscomp.JSError[], global::com.google.javascript.jscomp.JSError>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_getMessages22));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String toSource() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_toSource23));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/JSModule;)Ljava/lang/String;")]
        public virtual global::java.lang.String toSource(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_toSource24, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/Compiler$CodeBuilder;ILcom/google/javascript/rhino" +
            "/Node;)V")]
        public virtual void toSource(global::java.lang.Object par0, int par1, global::java.lang.Object par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_toSource25, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/ErrorManager;)V")]
        public virtual void setErrorManager(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_setErrorManager26, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void rebuildInputsFromModules() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_rebuildInputsFromModules27);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/util/List;Ljava/util/List;Lcom/google/javascript/jscomp/CompilerOptions;)L" +
            "com/google/javascript/jscomp/Result;")]
        public virtual global::com.google.javascript.jscomp.Result compileModules(global::java.util.List par0, global::java.util.List par1, global::com.google.javascript.jscomp.CompilerOptions par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.Result>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_compileModules28, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.util.List>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.util.List>(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void disableThreads() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_disableThreads29);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/PassConfig;)V")]
        public virtual void setPassConfig(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_setPassConfig30, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lcom/google/javascript/jscomp/MemoizedScopeCreator;")]
        public virtual global::java.lang.Object getTypedScopeCreator() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_getTypedScopeCreator31));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lcom/google/javascript/jscomp/SymbolTable;")]
        public virtual global::java.lang.Object buildKnownSymbolTable() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_buildKnownSymbolTable32));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/JSModule;)[Ljava/lang/String;")]
        public virtual java.lang.String[] toSourceArray(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_toSourceArray33, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()[Ljava/lang/String;")]
        public virtual java.lang.String[] toSourceArray() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_toSourceArray34));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void processDefines() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_processDefines35);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public virtual int getErrorCount() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_getErrorCount36)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public virtual int getWarningCount() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_getWarningCount37)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/util/logging/Level;)V")]
        public static void setLoggingLevel(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::com.google.javascript.jscomp.Compiler.staticClass, global::com.google.javascript.jscomp.Compiler.j4n_setLoggingLevel38, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getAstDotGraph() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_getAstDotGraph39));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/util/Map;")]
        public virtual global::java.util.Map getInputsById() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.Map>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_getInputsById40));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/JsAst;)V")]
        public virtual void replaceScript(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_replaceScript41, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public static global::java.lang.String getReleaseVersion() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.Compiler.staticClass, global::com.google.javascript.jscomp.Compiler.j4n_getReleaseVersion42));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public static global::java.lang.String getReleaseDate() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.Compiler.staticClass, global::com.google.javascript.jscomp.Compiler.j4n_getReleaseDate43));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lcom/google/javascript/jscomp/CompilerOptions$LanguageMode;")]
        public virtual global::java.lang.Object languageMode() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_languageMode44));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lcom/google/javascript/jscomp/SourceMap;")]
        public virtual global::java.lang.Object getSourceMap() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.Compiler.j4n_getSourceMap45));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/JsAst;)V")]
        public virtual void addNewScript(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.Compiler.j4n_addNewScript46, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.google.javascript.jscomp.Compiler(@__env);
            }
        }
    }
    #endregion
}
