//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.google.javascript.jscomp {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class JSSourceFile : global::com.google.javascript.jscomp.SourceFile, global::java.io.Serializable {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromFile0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromFile1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromFile2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromFile3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromCode4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromInputStream5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromGenerator6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorJSSourceFile7;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Lcom/google/javascript/jscomp/SourceFile;)V")]
        public JSSourceFile(global::com.google.javascript.jscomp.SourceFile par0) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.NewObject(global::com.google.javascript.jscomp.JSSourceFile.staticClass, global::com.google.javascript.jscomp.JSSourceFile.j4n__ctorJSSourceFile7, this, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        protected JSSourceFile(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.google.javascript.jscomp.JSSourceFile.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.google.javascript.jscomp.JSSourceFile.staticClass = @__class;
            global::com.google.javascript.jscomp.JSSourceFile.j4n_fromFile0 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.JSSourceFile.staticClass, "fromFile", "(Ljava/io/File;Ljava/nio/charset/Charset;)Lcom/google/javascript/jscomp/JSSourceF" +
                    "ile;");
            global::com.google.javascript.jscomp.JSSourceFile.j4n_fromFile1 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.JSSourceFile.staticClass, "fromFile", "(Ljava/lang/String;)Lcom/google/javascript/jscomp/JSSourceFile;");
            global::com.google.javascript.jscomp.JSSourceFile.j4n_fromFile2 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.JSSourceFile.staticClass, "fromFile", "(Ljava/io/File;)Lcom/google/javascript/jscomp/JSSourceFile;");
            global::com.google.javascript.jscomp.JSSourceFile.j4n_fromFile3 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.JSSourceFile.staticClass, "fromFile", "(Ljava/lang/String;Ljava/nio/charset/Charset;)Lcom/google/javascript/jscomp/JSSou" +
                    "rceFile;");
            global::com.google.javascript.jscomp.JSSourceFile.j4n_fromCode4 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.JSSourceFile.staticClass, "fromCode", "(Ljava/lang/String;Ljava/lang/String;)Lcom/google/javascript/jscomp/JSSourceFile;" +
                    "");
            global::com.google.javascript.jscomp.JSSourceFile.j4n_fromInputStream5 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.JSSourceFile.staticClass, "fromInputStream", "(Ljava/lang/String;Ljava/io/InputStream;)Lcom/google/javascript/jscomp/JSSourceFi" +
                    "le;");
            global::com.google.javascript.jscomp.JSSourceFile.j4n_fromGenerator6 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.JSSourceFile.staticClass, "fromGenerator", "(Ljava/lang/String;Lcom/google/javascript/jscomp/SourceFile$Generator;)Lcom/googl" +
                    "e/javascript/jscomp/JSSourceFile;");
            global::com.google.javascript.jscomp.JSSourceFile.j4n__ctorJSSourceFile7 = @__env.GetMethodID(global::com.google.javascript.jscomp.JSSourceFile.staticClass, "<init>", "(Lcom/google/javascript/jscomp/SourceFile;)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/io/File;Ljava/nio/charset/Charset;)Lcom/google/javascript/jscomp/JSSourceF" +
            "ile;")]
        public static global::com.google.javascript.jscomp.JSSourceFile fromFile(global::java.io.File par0, global::java.lang.Object par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.JSSourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.JSSourceFile.staticClass, global::com.google.javascript.jscomp.JSSourceFile.j4n_fromFile0, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/google/javascript/jscomp/JSSourceFile;")]
        public static global::com.google.javascript.jscomp.JSSourceFile fromFile(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.JSSourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.JSSourceFile.staticClass, global::com.google.javascript.jscomp.JSSourceFile.j4n_fromFile1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/io/File;)Lcom/google/javascript/jscomp/JSSourceFile;")]
        public static global::com.google.javascript.jscomp.JSSourceFile fromFile(global::java.io.File par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.JSSourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.JSSourceFile.staticClass, global::com.google.javascript.jscomp.JSSourceFile.j4n_fromFile2, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/nio/charset/Charset;)Lcom/google/javascript/jscomp/JSSou" +
            "rceFile;")]
        public static global::com.google.javascript.jscomp.JSSourceFile fromFile(global::java.lang.String par0, global::java.lang.Object par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.JSSourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.JSSourceFile.staticClass, global::com.google.javascript.jscomp.JSSourceFile.j4n_fromFile3, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;)Lcom/google/javascript/jscomp/JSSourceFile;" +
            "")]
        public static global::com.google.javascript.jscomp.JSSourceFile fromCode(global::java.lang.String par0, global::java.lang.String par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.JSSourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.JSSourceFile.staticClass, global::com.google.javascript.jscomp.JSSourceFile.j4n_fromCode4, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/io/InputStream;)Lcom/google/javascript/jscomp/JSSourceFi" +
            "le;")]
        public static global::com.google.javascript.jscomp.JSSourceFile fromInputStream(global::java.lang.String par0, global::java.io.InputStream par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.JSSourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.JSSourceFile.staticClass, global::com.google.javascript.jscomp.JSSourceFile.j4n_fromInputStream5, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Lcom/google/javascript/jscomp/SourceFile$Generator;)Lcom/googl" +
            "e/javascript/jscomp/JSSourceFile;")]
        public static global::com.google.javascript.jscomp.JSSourceFile fromGenerator(global::java.lang.String par0, global::java.lang.Object par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.JSSourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.JSSourceFile.staticClass, global::com.google.javascript.jscomp.JSSourceFile.j4n_fromGenerator6, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par1)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.google.javascript.jscomp.JSSourceFile(@__env);
            }
        }
    }
    #endregion
}
