//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.google.javascript.jscomp {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class SourceFile : global::java.lang.Object, global::java.io.Serializable {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getName0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isExtern1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getLineOffset2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getLineOfOffset3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getColumnOfOffset4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getRegion5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getCode6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromFile7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromFile8;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromFile9;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromFile10;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromCode11;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromCode12;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getLine13;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_builder14;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromReader15;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromInputStream16;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromInputStream17;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_fromGenerator18;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_clearCachedSource19;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getCodeReader20;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getOriginalPath21;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setOriginalPath22;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorSourceFile23;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)V")]
        public SourceFile(global::java.lang.String par0) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.NewObject(global::com.google.javascript.jscomp.SourceFile.staticClass, global::com.google.javascript.jscomp.SourceFile.j4n__ctorSourceFile23, this, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        protected SourceFile(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.google.javascript.jscomp.SourceFile.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.google.javascript.jscomp.SourceFile.staticClass = @__class;
            global::com.google.javascript.jscomp.SourceFile.j4n_getName0 = @__env.GetMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "getName", "()Ljava/lang/String;");
            global::com.google.javascript.jscomp.SourceFile.j4n_isExtern1 = @__env.GetMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "isExtern", "()Z");
            global::com.google.javascript.jscomp.SourceFile.j4n_getLineOffset2 = @__env.GetMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "getLineOffset", "(I)I");
            global::com.google.javascript.jscomp.SourceFile.j4n_getLineOfOffset3 = @__env.GetMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "getLineOfOffset", "(I)I");
            global::com.google.javascript.jscomp.SourceFile.j4n_getColumnOfOffset4 = @__env.GetMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "getColumnOfOffset", "(I)I");
            global::com.google.javascript.jscomp.SourceFile.j4n_getRegion5 = @__env.GetMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "getRegion", "(I)Lcom/google/javascript/jscomp/Region;");
            global::com.google.javascript.jscomp.SourceFile.j4n_getCode6 = @__env.GetMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "getCode", "()Ljava/lang/String;");
            global::com.google.javascript.jscomp.SourceFile.j4n_fromFile7 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "fromFile", "(Ljava/io/File;)Lcom/google/javascript/jscomp/SourceFile;");
            global::com.google.javascript.jscomp.SourceFile.j4n_fromFile8 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "fromFile", "(Ljava/io/File;Ljava/nio/charset/Charset;)Lcom/google/javascript/jscomp/SourceFil" +
                    "e;");
            global::com.google.javascript.jscomp.SourceFile.j4n_fromFile9 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "fromFile", "(Ljava/lang/String;)Lcom/google/javascript/jscomp/SourceFile;");
            global::com.google.javascript.jscomp.SourceFile.j4n_fromFile10 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "fromFile", "(Ljava/lang/String;Ljava/nio/charset/Charset;)Lcom/google/javascript/jscomp/Sourc" +
                    "eFile;");
            global::com.google.javascript.jscomp.SourceFile.j4n_fromCode11 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "fromCode", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/google/javascript/js" +
                    "comp/SourceFile;");
            global::com.google.javascript.jscomp.SourceFile.j4n_fromCode12 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "fromCode", "(Ljava/lang/String;Ljava/lang/String;)Lcom/google/javascript/jscomp/SourceFile;");
            global::com.google.javascript.jscomp.SourceFile.j4n_getLine13 = @__env.GetMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "getLine", "(I)Ljava/lang/String;");
            global::com.google.javascript.jscomp.SourceFile.j4n_builder14 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "builder", "()Lcom/google/javascript/jscomp/SourceFile$Builder;");
            global::com.google.javascript.jscomp.SourceFile.j4n_fromReader15 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "fromReader", "(Ljava/lang/String;Ljava/io/Reader;)Lcom/google/javascript/jscomp/SourceFile;");
            global::com.google.javascript.jscomp.SourceFile.j4n_fromInputStream16 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "fromInputStream", "(Ljava/lang/String;Ljava/lang/String;Ljava/io/InputStream;)Lcom/google/javascript" +
                    "/jscomp/SourceFile;");
            global::com.google.javascript.jscomp.SourceFile.j4n_fromInputStream17 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "fromInputStream", "(Ljava/lang/String;Ljava/io/InputStream;)Lcom/google/javascript/jscomp/SourceFile" +
                    ";");
            global::com.google.javascript.jscomp.SourceFile.j4n_fromGenerator18 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "fromGenerator", "(Ljava/lang/String;Lcom/google/javascript/jscomp/SourceFile$Generator;)Lcom/googl" +
                    "e/javascript/jscomp/SourceFile;");
            global::com.google.javascript.jscomp.SourceFile.j4n_clearCachedSource19 = @__env.GetMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "clearCachedSource", "()V");
            global::com.google.javascript.jscomp.SourceFile.j4n_getCodeReader20 = @__env.GetMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "getCodeReader", "()Ljava/io/Reader;");
            global::com.google.javascript.jscomp.SourceFile.j4n_getOriginalPath21 = @__env.GetMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "getOriginalPath", "()Ljava/lang/String;");
            global::com.google.javascript.jscomp.SourceFile.j4n_setOriginalPath22 = @__env.GetMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "setOriginalPath", "(Ljava/lang/String;)V");
            global::com.google.javascript.jscomp.SourceFile.j4n__ctorSourceFile23 = @__env.GetMethodID(global::com.google.javascript.jscomp.SourceFile.staticClass, "<init>", "(Ljava/lang/String;)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getName() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.SourceFile.j4n_getName0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public virtual bool isExtern() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::com.google.javascript.jscomp.SourceFile.j4n_isExtern1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)I")]
        public virtual int getLineOffset(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((int)(@__env.CallIntMethod(this, global::com.google.javascript.jscomp.SourceFile.j4n_getLineOffset2, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)I")]
        public virtual int getLineOfOffset(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((int)(@__env.CallIntMethod(this, global::com.google.javascript.jscomp.SourceFile.j4n_getLineOfOffset3, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)I")]
        public virtual int getColumnOfOffset(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((int)(@__env.CallIntMethod(this, global::com.google.javascript.jscomp.SourceFile.j4n_getColumnOfOffset4, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)Lcom/google/javascript/jscomp/Region;")]
        public virtual global::java.lang.Object getRegion(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.SourceFile.j4n_getRegion5, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getCode() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.SourceFile.j4n_getCode6));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/io/File;)Lcom/google/javascript/jscomp/SourceFile;")]
        public static global::com.google.javascript.jscomp.SourceFile fromFile(global::java.io.File par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.SourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.SourceFile.staticClass, global::com.google.javascript.jscomp.SourceFile.j4n_fromFile7, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/io/File;Ljava/nio/charset/Charset;)Lcom/google/javascript/jscomp/SourceFil" +
            "e;")]
        public static global::com.google.javascript.jscomp.SourceFile fromFile(global::java.io.File par0, global::java.lang.Object par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.SourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.SourceFile.staticClass, global::com.google.javascript.jscomp.SourceFile.j4n_fromFile8, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)Lcom/google/javascript/jscomp/SourceFile;")]
        public static global::com.google.javascript.jscomp.SourceFile fromFile(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.SourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.SourceFile.staticClass, global::com.google.javascript.jscomp.SourceFile.j4n_fromFile9, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/nio/charset/Charset;)Lcom/google/javascript/jscomp/Sourc" +
            "eFile;")]
        public static global::com.google.javascript.jscomp.SourceFile fromFile(global::java.lang.String par0, global::java.lang.Object par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.SourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.SourceFile.staticClass, global::com.google.javascript.jscomp.SourceFile.j4n_fromFile10, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/google/javascript/js" +
            "comp/SourceFile;")]
        public static global::com.google.javascript.jscomp.SourceFile fromCode(global::java.lang.String par0, global::java.lang.String par1, global::java.lang.String par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.SourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.SourceFile.staticClass, global::com.google.javascript.jscomp.SourceFile.j4n_fromCode11, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;)Lcom/google/javascript/jscomp/SourceFile;")]
        public static global::com.google.javascript.jscomp.SourceFile fromCode(global::java.lang.String par0, global::java.lang.String par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.SourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.SourceFile.staticClass, global::com.google.javascript.jscomp.SourceFile.j4n_fromCode12, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)Ljava/lang/String;")]
        public virtual global::java.lang.String getLine(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.SourceFile.j4n_getLine13, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lcom/google/javascript/jscomp/SourceFile$Builder;")]
        public static global::java.lang.Object builder() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.SourceFile.staticClass, global::com.google.javascript.jscomp.SourceFile.j4n_builder14));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/io/Reader;)Lcom/google/javascript/jscomp/SourceFile;")]
        public static global::com.google.javascript.jscomp.SourceFile fromReader(global::java.lang.String par0, global::java.lang.Object par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.SourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.SourceFile.staticClass, global::com.google.javascript.jscomp.SourceFile.j4n_fromReader15, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/lang/String;Ljava/io/InputStream;)Lcom/google/javascript" +
            "/jscomp/SourceFile;")]
        public static global::com.google.javascript.jscomp.SourceFile fromInputStream(global::java.lang.String par0, global::java.lang.String par1, global::java.io.InputStream par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.SourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.SourceFile.staticClass, global::com.google.javascript.jscomp.SourceFile.j4n_fromInputStream16, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Ljava/io/InputStream;)Lcom/google/javascript/jscomp/SourceFile" +
            ";")]
        public static global::com.google.javascript.jscomp.SourceFile fromInputStream(global::java.lang.String par0, global::java.io.InputStream par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.SourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.SourceFile.staticClass, global::com.google.javascript.jscomp.SourceFile.j4n_fromInputStream17, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;Lcom/google/javascript/jscomp/SourceFile$Generator;)Lcom/googl" +
            "e/javascript/jscomp/SourceFile;")]
        public static global::com.google.javascript.jscomp.SourceFile fromGenerator(global::java.lang.String par0, global::java.lang.Object par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::com.google.javascript.jscomp.SourceFile>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.SourceFile.staticClass, global::com.google.javascript.jscomp.SourceFile.j4n_fromGenerator18, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void clearCachedSource() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.SourceFile.j4n_clearCachedSource19);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/io/Reader;")]
        public virtual global::java.lang.Object getCodeReader() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.SourceFile.j4n_getCodeReader20));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getOriginalPath() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.google.javascript.jscomp.SourceFile.j4n_getOriginalPath21));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;)V")]
        public virtual void setOriginalPath(global::java.lang.String par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.google.javascript.jscomp.SourceFile.j4n_setOriginalPath22, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.google.javascript.jscomp.SourceFile(@__env);
            }
        }
    }
    #endregion
}
