//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.google.javascript.jscomp {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class CommandLineRunner : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_main0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getDefaultExterns1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_shouldRunCompiler2;
        
        protected CommandLineRunner(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.google.javascript.jscomp.CommandLineRunner.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.google.javascript.jscomp.CommandLineRunner.staticClass = @__class;
            global::com.google.javascript.jscomp.CommandLineRunner.j4n_main0 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.CommandLineRunner.staticClass, "main", "([Ljava/lang/String;)V");
            global::com.google.javascript.jscomp.CommandLineRunner.j4n_getDefaultExterns1 = @__env.GetStaticMethodID(global::com.google.javascript.jscomp.CommandLineRunner.staticClass, "getDefaultExterns", "()Ljava/util/List;");
            global::com.google.javascript.jscomp.CommandLineRunner.j4n_shouldRunCompiler2 = @__env.GetMethodID(global::com.google.javascript.jscomp.CommandLineRunner.staticClass, "shouldRunCompiler", "()Z");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("([Ljava/lang/String;)V")]
        public static void main(java.lang.String[] par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::com.google.javascript.jscomp.CommandLineRunner.staticClass, global::com.google.javascript.jscomp.CommandLineRunner.j4n_main0, global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/util/List;")]
        public static global::java.util.List getDefaultExterns() {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.util.List>(@__env, @__env.CallStaticObjectMethodPtr(global::com.google.javascript.jscomp.CommandLineRunner.staticClass, global::com.google.javascript.jscomp.CommandLineRunner.j4n_getDefaultExterns1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public virtual bool shouldRunCompiler() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::com.google.javascript.jscomp.CommandLineRunner.j4n_shouldRunCompiler2)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.google.javascript.jscomp.CommandLineRunner(@__env);
            }
        }
    }
    #endregion
}
